-- Insert sample products for Can I Eat app
INSERT INTO public.products (
  name, 
  brand, 
  description, 
  image_url, 
  ingredients, 
  health_score, 
  is_vegetarian, 
  is_vegan, 
  is_gluten_free, 
  is_organic, 
  is_published, 
  category, 
  subcategory, 
  tags,
  user_submitted
) VALUES
-- Trending Products
(
  'Organic Greek Yogurt', 
  'Amul', 
  'Rich and creamy Greek yogurt made with organic milk', 
  'https://images.unsplash.com/photo-1488477181946-6428a0291777?q=80&w=1000', 
  'Organic milk, live cultures', 
  85, 
  true, 
  false, 
  true, 
  true, 
  true, 
  'Dairy', 
  'Yogurt', 
  ARRAY['protein-rich', 'probiotic', 'calcium'],
  false
),
(
  'Multigrain Bread', 
  'Britannia', 
  'Nutritious multigrain bread with 7 whole grains', 
  'https://images.unsplash.com/photo-1509440159596-0249088772ff?q=80&w=1000', 
  'Whole wheat flour, oats, flax seeds, sunflower seeds, pumpkin seeds, millet, quinoa, water, yeast, salt', 
  78, 
  true, 
  true, 
  false, 
  false, 
  true, 
  'Bakery', 
  'Bread', 
  ARRAY['fiber-rich', 'whole-grain'],
  false
),
(
  'Dark Chocolate Bar', 
  'Cadbury', 
  '72% cocoa dark chocolate with antioxidant properties', 
  'https://images.unsplash.com/photo-1606312619070-d48b4c652a52?q=80&w=1000', 
  'Cocoa mass, cocoa butter, sugar, vanilla extract', 
  65, 
  true, 
  true, 
  true, 
  false, 
  true, 
  'Sweets', 
  'Chocolate', 
  ARRAY['antioxidant', 'mood-booster'],
  false
),
(
  'Masala Oats', 
  'Saffola', 
  'Quick cooking masala flavored oats', 
  'https://images.unsplash.com/photo-1584473457409-ce95a9573e86?q=80&w=1000', 
  'Rolled oats, spices (turmeric, cumin, coriander), dehydrated vegetables, salt', 
  80, 
  true, 
  true, 
  false, 
  false, 
  true, 
  'Cereals', 
  'Oats', 
  ARRAY['fiber-rich', 'quick-breakfast'],
  false
),
(
  'Olive Oil Extra Virgin', 
  'Borges', 
  'Cold-pressed extra virgin olive oil', 
  'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?q=80&w=1000', 
  'Extra virgin olive oil', 
  90, 
  true, 
  true, 
  true, 
  true, 
  true, 
  'Condiments', 
  'Oils', 
  ARRAY['heart-healthy', 'antioxidant'],
  false
),
-- Categories: Dairy products
(
  'Paneer', 
  'Mother Dairy', 
  'Fresh cottage cheese made from pure milk', 
  'https://images.unsplash.com/photo-1631452180519-c014fe946bc7?q=80&w=1000', 
  'Milk, citric acid', 
  70, 
  true, 
  false, 
  true, 
  false, 
  true, 
  'Dairy', 
  'Cheese', 
  ARRAY['protein-rich', 'calcium'],
  false
),
(
  'Butter', 
  'Amul', 
  'Pasteurized butter made from cow''s milk',
  'https://images.unsplash.com/photo-1589985270958-a664e7dc9ea4?q=80&w=1000', 
  'Milk fat, water, salt', 
  50, 
  true, 
  false, 
  true, 
  false, 
  true, 
  'Dairy', 
  'Butter', 
  ARRAY['fat', 'vitamin A'],
  false
),
-- Categories: Snacks
(
  'Roasted Almonds', 
  'Happilo', 
  'Dry roasted almonds with no added salt', 
  'https://images.unsplash.com/photo-1574164052277-b9ea797fb7a7?q=80&w=1000', 
  'Almonds', 
  85, 
  true, 
  true, 
  true, 
  true, 
  true, 
  'Snacks', 
  'Nuts', 
  ARRAY['protein', 'vitamin E', 'healthy-fats'],
  false
),
(
  'Potato Chips Classic', 
  'Lays', 
  'Classic salted potato chips', 
  'https://images.unsplash.com/photo-1613919113640-25732ec5e61f?q=80&w=1000', 
  'Potatoes, vegetable oil, salt', 
  40, 
  true, 
  true, 
  true, 
  false, 
  true, 
  'Snacks', 
  'Chips', 
  ARRAY['crispy', 'salted'],
  false
),
-- Categories: Beverages
(
  'Green Tea', 
  'Lipton', 
  'Pure green tea leaves with antioxidants', 
  'https://images.unsplash.com/photo-1627435601361-ec25f5b5be0f?q=80&w=1000', 
  'Green tea leaves', 
  92, 
  true, 
  true, 
  true, 
  false, 
  true, 
  'Beverages', 
  'Tea', 
  ARRAY['antioxidant', 'metabolism-booster', 'calming'],
  false
),
(
  'Orange Juice', 
  'Tropicana', 
  '100% fresh orange juice with no added sugar', 
  'https://images.unsplash.com/photo-1600271886742-f049cd451bba?q=80&w=1000', 
  'Orange juice', 
  75, 
  true, 
  true, 
  true, 
  false, 
  true, 
  'Beverages', 
  'Juice', 
  ARRAY['vitamin C', 'refreshing'],
  false
),
-- Various dietary support options
(
  'Vegan Protein Powder', 
  'MuscleBlaze', 
  'Plant-based protein powder for vegans', 
  'https://images.unsplash.com/photo-1594294271963-e7f0ef38dfff?q=80&w=1000', 
  'Pea protein isolate, brown rice protein, natural flavoring, stevia', 
  88, 
  true, 
  true, 
  true, 
  false, 
  true, 
  'Health Supplements', 
  'Protein', 
  ARRAY['vegan', 'protein-rich', 'workout'],
  false
),
(
  'Gluten-Free Pasta', 
  'Barilla', 
  'Pasta made from corn and rice flour, gluten-free', 
  'https://images.unsplash.com/photo-1612817288484-6f916006741a?q=80&w=1000', 
  'Corn flour, rice flour, water', 
  70, 
  true, 
  true, 
  true, 
  false, 
  true, 
  'Cereals', 
  'Pasta', 
  ARRAY['gluten-free', 'easy-cook'],
  false
),
(
  'Organic Turmeric Powder', 
  'Organic India', 
  'USDA certified organic turmeric powder', 
  'https://images.unsplash.com/photo-1615485500704-8e990f9671f1?q=80&w=1000', 
  'Organic turmeric', 
  95, 
  true, 
  true, 
  true, 
  true, 
  true, 
  'Spices', 
  'Ground Spices', 
  ARRAY['anti-inflammatory', 'organic', 'antioxidant'],
  false
),
-- Featured Health Insights products
(
  'Chia Seeds', 
  'True Elements', 
  'Nutrient-dense chia seeds rich in omega-3', 
  'https://images.unsplash.com/photo-1519594445288-63d845f8b7cb?q=80&w=1000', 
  'Chia seeds', 
  93, 
  true, 
  true, 
  true, 
  true, 
  true, 
  'Superfoods', 
  'Seeds', 
  ARRAY['omega-3', 'fiber', 'protein'],
  false
),
(
  'Honey', 
  'Dabur', 
  'Pure raw honey with no additives', 
  'https://images.unsplash.com/photo-1587049352851-8d4e89133924?q=80&w=1000', 
  'Raw honey', 
  80, 
  true, 
  false, 
  true, 
  true, 
  true, 
  'Condiments', 
  'Sweeteners', 
  ARRAY['natural-sweetener', 'antibacterial'],
  false
),
(
  'Quinoa', 
  'India Gate', 
  'White quinoa seeds, complete protein source', 
  'https://images.unsplash.com/photo-1586201375761-83865001e8ac?q=80&w=1000', 
  'Quinoa seeds', 
  90, 
  true, 
  true, 
  true, 
  true, 
  true, 
  'Cereals', 
  'Grains', 
  ARRAY['complete-protein', 'fiber', 'gluten-free'],
  false
),
-- Add a few user-submitted products that need approval
(
  'Traditional Bhujia', 
  'Haldiram''s', 
  'Spicy and crunchy traditional Indian snack', 
  'https://images.unsplash.com/photo-1599302592205-d7d683634714?q=80&w=1000', 
  'Gram flour, palm oil, spices, salt', 
  55, 
  true, 
  true, 
  true, 
  false, 
  false, 
  'Snacks', 
  'Namkeen', 
  ARRAY['spicy', 'crunchy', 'traditional'],
  true
),
(
  'Millet Cookies', 
  'Early Foods', 
  'Healthy cookies made with millet flour and jaggery', 
  'https://images.unsplash.com/photo-1601490622651-99d507e5452b?q=80&w=1000', 
  'Millet flour, ghee, jaggery, cardamom', 
  75, 
  true, 
  false, 
  true, 
  true, 
  false, 
  'Bakery', 
  'Cookies', 
  ARRAY['whole-grain', 'traditional-sweetener'],
  true
);